version: '3'

services:
  room9_db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=room9
    ports:
    - 3306:3306
    volumes:
    - ./db_volume:/var/lib/mysql
